(part "2336582-1"
    (packageRef "23365821")
    (interface
        (port "C1" (symbPinId 1) (portName "VCC") (portType INOUT))
        (port "C2" (symbPinId 2) (portName "RST") (portType INOUT))
        (port "C3" (symbPinId 3) (portName "CLK") (portType INOUT))
        (port "C5" (symbPinId 4) (portName "GND") (portType INOUT))
        (port "C6" (symbPinId 5) (portName "VPP") (portType INOUT))
        (port "C7" (symbPinId 6) (portName "I/O") (portType INOUT))
        (port "CD1" (symbPinId 7) (portName "CD1") (portType INOUT))
        (port "MP1" (symbPinId 8) (portName "MP1") (portType INOUT))
        (port "MP2" (symbPinId 9) (portName "MP2") (portType INOUT))
        (port "MP3" (symbPinId 10) (portName "MP3") (portType INOUT))
        (port "MP4" (symbPinId 11) (portName "MP4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "2336582-1")
    (property "Description" "4FF SIM, Push-Push Type, 7 Position, 7 Loaded Positions, Signal, -40  80 C [-40  185 F], SIM Card Connectors")
    (property "Datasheet_Link" "https://www.te.com/en/product-2336582-1.html")
    (property "symbolName1" "2336582-1")
)
