(part "662104231722"
    (packageRef "662104231722")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "MP1" (symbPinId 5) (portName "MP1") (portType INOUT))
        (port "MP2" (symbPinId 6) (portName "MP2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Newark_Part_Number" "")
    (property "Newark_Price/Stock" "")
    (property "Manufacturer_Name" "Wurth Elektronik")
    (property "Manufacturer_Part_Number" "662104231722")
    (property "Description" "WR-MPC3 Micro Power Connectors 3.00 mm SMT Dual Row Male Header Right Angled with SMT Solder Tabs - Tin Plating - Glow-Wire, 04 Pins")
    (property "Datasheet_Link" "https://www.we-online.com/components/products/download/3D_662104231722+%28rev1%29.pdf")
    (property "symbolName1" "662104231722")
)
