(part "LM74610QDGKRQ1"
    (packageRef "SOP65P490X110-8N")
    (interface
        (port "1" (symbPinId 1) (portName "VCAPL") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GATE_PULL_DOWN") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NC_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "ANODE") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NC_2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "GATE_DRIVE") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VCAPH") (portType INOUT))
        (port "8" (symbPinId 8) (portName "CATHODE") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-LM74610QDGKRQ1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/LM74610QDGKRQ1?qs=3jdCaFhktOQTVpuuubgDqg%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "LM74610QDGKRQ1")
    (property "Description" "Zero Iq Reverse Polarity Protection Smart Diode Controller")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/lm74610-q1")
    (property "symbolName1" "LM74610QDGKRQ1")
)
