(part "AP63301WU-7"
    (packageRef "SOT95P280X100-6N")
    (interface
        (port "1" (symbPinId 1) (portName "FB") (portType INOUT))
        (port "2" (symbPinId 2) (portName "EN") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VIN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND") (portType INOUT))
        (port "5" (symbPinId 5) (portName "SW") (portType INOUT))
        (port "6" (symbPinId 6) (portName "BST") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "621-AP63301WU-7")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Diodes-Incorporated/AP63301WU-7?qs=bZr6mbWTK5mxozg17S0lNg%3D%3D")
    (property "Manufacturer_Name" "Diodes Incorporated")
    (property "Manufacturer_Part_Number" "AP63301WU-7")
    (property "Description" "3.8V TO 32V INPUT, 3A LOW IQ SYNCHRONOUS BUCK WITH ENHANCED EMI REDUCTION.")
    (property "Datasheet_Link" "https://www.diodes.com//assets/Datasheets/AP63300-AP63301.pdf")
    (property "symbolName1" "AP63301WU-7")
)
