(part "BLM18KG221BH1D"
    (packageRef "BLM18AG102BH1D")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "155")
    (property "Mouser_Part_Number" "81-BLM18KG221BH1D")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Murata-Electronics/BLM18KG221BH1D?qs=sJ5gq5MLFXpgEHYBdWUtkQ%3D%3D")
    (property "Manufacturer_Name" "Murata Electronics")
    (property "Manufacturer_Part_Number" "BLM18KG221BH1D")
    (property "Description" "BLM18_H1D Series EMI Suppression Filter 220+/-25% at 100MHz 1.5A @85")
    (property "Datasheet_Link" "https://www.murata.com/en-us/products/productdetail?partno=BLM18KG221BH1%23")
    (property "symbolName1" "BLM18KG221BH1D")
)
