(part "MPZ1608S102ATA00"
    (packageRef "BEADC1608X95N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "810-MPZ1608S102ATA00")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TDK/MPZ1608S102ATA00?qs=8Kz9Wu9QwqXjw56MUD5REw%3D%3D")
    (property "Manufacturer_Name" "TDK")
    (property "Manufacturer_Part_Number" "MPZ1608S102ATA00")
    (property "Description" "1 kOhms @ 100MHz 1 Power Line Ferrite Bead 0603 (1608 Metric) 800mA 300mOhm")
    (property "Datasheet_Link" "https://product.tdk.com/system/files/dam/doc/product/emc/emc/beads/catalog/beads_commercial_power_mpz1608_en.pdf")
    (property "symbolName1" "MPZ1608S102ATA00")
)
