(part "CGA2B3X7R1H333K050BB"
    (packageRef "CAPC1005X55N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "810-CGA2B3X7R1H333K")
    (property "Mouser_Price/Stock" "https://www.mouser.com/Search/Refine.aspx?Keyword=810-CGA2B3X7R1H333K")
    (property "Manufacturer_Name" "TDK")
    (property "Manufacturer_Part_Number" "CGA2B3X7R1H333K050BB")
    (property "Description" "Multilayer Ceramic Chip Capacitors, Capacitance=33nF, LxWxT:1x0.5x0.5mm")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/CGA2B3X7R1H333K050BB.pdf")
    (property "symbolName1" "CGA2B3X7R1H333K050BB")
)
