(part "LQH3NPZ100MJRL"
    (packageRef "LQH3NPN100MJRL")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Mouser_Part_Number" "81-LQH3NPZ100MJRL")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Murata-Electronics/LQH3NPZ100MJRL?qs=Ey7%2FXF42M3e2EdJiitgVwQ%3D%3D")
    (property "Manufacturer_Name" "Murata Electronics")
    (property "Manufacturer_Part_Number" "LQH3NPZ100MJRL")
    (property "Description" "LQH3NPZ_JR Series Inductor 10uH +/-20% 1212 (3030)")
    (property "Datasheet_Link" "https://search.murata.co.jp/Ceramy/image/img/P02/JELF243A-9131.pdf")
    (property "symbolName1" "LQH3NPZ100MJRL")
)
