SamacSys ECAD Model
555981/941407/2.50/3/2/Connector

DESIGNSPARK_INTERMEDIATE_ASCII

(asciiHeader
	(fileUnits MM)
)
(library Library_1
	(padStyleDef "r220_105"
		(holeDiam 0)
		(padShape (layerNumRef 1) (padShapeType Rect)  (shapeWidth 1.05) (shapeHeight 2.2))
		(padShape (layerNumRef 16) (padShapeType Ellipse)  (shapeWidth 0) (shapeHeight 0))
	)
	(padStyleDef "r105_100"
		(holeDiam 0)
		(padShape (layerNumRef 1) (padShapeType Rect)  (shapeWidth 1) (shapeHeight 1.05))
		(padShape (layerNumRef 16) (padShapeType Ellipse)  (shapeWidth 0) (shapeHeight 0))
	)
	(textStyleDef "Default"
		(font
			(fontType Stroke)
			(fontFace "Helvetica")
			(fontHeight 50 mils)
			(strokeWidth 5 mils)
		)
	)
	(patternDef "1909763-1" (originalName "1909763-1")
		(multiLayer
			(pad (padNum 1) (padStyleRef r220_105) (pt -1.475, 0) (rotation 0))
			(pad (padNum 2) (padStyleRef r105_100) (pt 0, -1.525) (rotation 0))
			(pad (padNum 3) (padStyleRef r220_105) (pt 1.475, 0) (rotation 0))
		)
		(layerContents (layerNumRef 18)
			(attr "RefDes" "RefDes" (pt -0.416, -0.058) (textStyleRef "Default") (isVisible True))
		)
		(layerContents (layerNumRef 28)
			(line (pt -1.5 1.3) (pt 1.5 1.3) (width 0.2))
		)
		(layerContents (layerNumRef 28)
			(line (pt 1.5 1.3) (pt 1.5 -1.3) (width 0.2))
		)
		(layerContents (layerNumRef 28)
			(line (pt 1.5 -1.3) (pt -1.5 -1.3) (width 0.2))
		)
		(layerContents (layerNumRef 28)
			(line (pt -1.5 -1.3) (pt -1.5 1.3) (width 0.2))
		)
		(layerContents (layerNumRef 18)
			(line (pt -1.5 1.3) (pt 1.5 1.3) (width 0.2))
		)
		(layerContents (layerNumRef 18)
			(line (pt -1.5 -1.3) (pt -0.83 -1.3) (width 0.2))
		)
		(layerContents (layerNumRef 18)
			(line (pt 1.5 -1.3) (pt 0.83 -1.3) (width 0.2))
		)
	)
	(symbolDef "1909763-1" (originalName "1909763-1")

		(pin (pinNum 1) (pt 800 mils 0 mils) (rotation 180) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 570 mils -25 mils) (rotation 0]) (justify "Right") (textStyleRef "Default"))
		))
		(pin (pinNum 2) (pt 0 mils 0 mils) (rotation 0) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 230 mils -25 mils) (rotation 0]) (justify "Left") (textStyleRef "Default"))
		))
		(pin (pinNum 3) (pt 800 mils -100 mils) (rotation 180) (pinLength 200 mils) (pinDisplay (dispPinName true)) (pinName (text (pt 570 mils -125 mils) (rotation 0]) (justify "Right") (textStyleRef "Default"))
		))
		(line (pt 200 mils 100 mils) (pt 600 mils 100 mils) (width 6 mils))
		(line (pt 600 mils 100 mils) (pt 600 mils -200 mils) (width 6 mils))
		(line (pt 600 mils -200 mils) (pt 200 mils -200 mils) (width 6 mils))
		(line (pt 200 mils -200 mils) (pt 200 mils 100 mils) (width 6 mils))
		(attr "RefDes" "RefDes" (pt 650 mils 300 mils) (justify Left) (isVisible True) (textStyleRef "Default"))

	)
	(compDef "1909763-1" (originalName "1909763-1") (compHeader (numPins 3) (numParts 1) (refDesPrefix J)
		)
		(compPin "1" (pinName "1") (partNum 1) (symPinNum 1) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "2" (pinName "2") (partNum 1) (symPinNum 2) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(compPin "3" (pinName "3") (partNum 1) (symPinNum 3) (gateEq 0) (pinEq 0) (pinType Bidirectional))
		(attachedSymbol (partNum 1) (altType Normal) (symbolName "1909763-1"))
		(attachedPattern (patternNum 1) (patternName "1909763-1")
			(numPads 3)
			(padPinMap
				(padNum 1) (compPinRef "1")
				(padNum 2) (compPinRef "2")
				(padNum 3) (compPinRef "3")
			)
		)
		(attr "Mouser Part Number" "571-1909763-1")
		(attr "Mouser Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity-AMP/1909763-1?qs=zR8VgEwoOb2%252BUqFkM9%2F6jQ%3D%3D")
		(attr "Manufacturer_Name" "TE Connectivity")
		(attr "Manufacturer_Part_Number" "1909763-1")
		(attr "Description" "Body Features: Cable Connector Orientation Straight | Body Material Finish Plated | Body Plating Material Gold Flash | Body Underplating Material Nickel | Body Material Copper Alloy | Configuration Features: Number of Positions 1 | Number of Coaxial Contacts 1 | PCB Mount Orientation Vertical | Contact Features: RF Connector Center Contact Material Copper Alloy | RF Connector Center Contact Plating Material Gold | Dimensions: RF Connector Mated Outer Diameter (Approximate) .078 INCH | Profile Height from PC")
		(attr "Datasheet Link" "http://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=1909763&DocType=Customer+Drawing&DocLang=English")
	)

)
