(part "BSS138PW_115"
    (packageRef "SOT65P210X110-3N")
    (interface
        (port "1" (symbPinId 1) (portName "G") (portType INOUT))
        (port "2" (symbPinId 2) (portName "S") (portType INOUT))
        (port "3" (symbPinId 3) (portName "D") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "771-BSS138PW115")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Nexperia/BSS138PW115?qs=A1cBxND5mHKdv5mYHLzmBw%3D%3D")
    (property "Manufacturer_Name" "Nexperia")
    (property "Manufacturer_Part_Number" "BSS138PW,115")
    (property "Description" "BSS138PW,115 N-Channel MOSFET, 320 mA, 60 V, 3-Pin SOT-323 Nexperia")
    (property "Datasheet_Link" "https://assets.nexperia.com/documents/data-sheet/BSS138PW.pdf")
    (property "symbolName1" "BSS138PW_115")
)
