(part "SMF16A"
    (packageRef "SODFL3618X110N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "576-SMF16A")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Littelfuse/SMF16A?qs=IP%252BaFeBnnar8T%2Ffm%252BJ%2Flrw%3D%3D")
    (property "Manufacturer_Name" "LITTELFUSE")
    (property "Manufacturer_Part_Number" "SMF16A")
    (property "Description" "ESD Suppressors / TVS Diodes 200W 16V 5% Uni-directional")
    (property "Datasheet_Link" "https://www.littelfuse.com/~/media/electronics/datasheets/tvs_diodes/littelfuse_tvs_diode_smf_datasheet.pdf.pdf")
    (property "symbolName1" "SMF16A")
)
