(part "2174507-2"
    (packageRef "21745072")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "MP1" (symbPinId 6) (portName "MP1") (portType INOUT))
        (port "MP2" (symbPinId 7) (portName "MP2") (portType INOUT))
        (port "MP3" (symbPinId 8) (portName "MP3") (portType INOUT))
        (port "MP4" (symbPinId 9) (portName "MP4") (portType INOUT))
        (port "MP5" (symbPinId 10) (portName "MP5") (portType INOUT))
        (port "MP6" (symbPinId 11) (portName "MP6") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "571-2174507-2")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity/2174507-2?qs=kAqyOuzYGe%252BUWCFD1qNBLQ%3D%3D")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "2174507-2")
    (property "Description" "Body Features: Shell Plating Material Reflowed Tin over Nickel | Offset 0 MM | Connector Profile Micro | Shell Plating Finish Bright | Configuration Features: Number of Ports 1 | Number of Positions 5 | Contact Features: Contact Mating Area Plating Material Thickness 29.52 MICIN | Contact Mating Area Plating Material Thickness .76 MICM | Contact Current Rating (Max) 1.8 AMP | Contact Mating Area Plating Material Gold | Dimensions: PCB Thickness (Recommended) .8  1. MM | PCB Thickness (Recommended) .031 ")
    (property "Datasheet_Link" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=srchrtrv&DocNm=5-1773464-3&DocType=Data%20Sheet&DocLang=English&PartCntxt=2174507-2&DocFormat=pdf")
    (property "symbolName1" "2174507-2")
)
