(part "AP2204R-5_0TRG1"
    (packageRef "AP2204R50TRG1")
    (interface
        (port "1" (symbPinId 1) (portName "VIN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VOUT") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "621-AP2204R-5.0TRG1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Diodes-Incorporated/AP2204R-5.0TRG1?qs=x6A8l6qLYDB4wt14AgubAw%3D%3D")
    (property "Manufacturer_Name" "Diodes Incorporated")
    (property "Manufacturer_Part_Number" "AP2204R-5.0TRG1")
    (property "Description" "LDO Voltage Regulators 150mA CMOS LDO 5.0V")
    (property "Datasheet_Link" "https://datasheet.lcsc.com/szlcsc/Diodes-Incorporated-AP2204R-5-0TRG1_C156388.pdf")
    (property "symbolName1" "AP2204R-5_0TRG1")
)
