(part "MUN5233T1G"
    (packageRef "SOT65P220X100-3N")
    (interface
        (port "1" (symbPinId 1) (portName "B") (portType INOUT))
        (port "2" (symbPinId 2) (portName "E") (portType INOUT))
        (port "3" (symbPinId 3) (portName "C") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "863-MUN5233T1G")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/onsemi/MUN5233T1G?qs=ZpPixqFcBtzWrnINWZxoIA%3D%3D")
    (property "Manufacturer_Name" "onsemi")
    (property "Manufacturer_Part_Number" "MUN5233T1G")
    (property "Description" "Simplifies Circuit Design; Reduces Component Count; S Prefix for Automotive and Other Applications Requiring Unique Site and Control Change Requirements; AEC-Q101 Qualified and PPAP Capable; These Devices are PbFree, Halogen Free/BFR Free and are RoHS Compliant")
    (property "Datasheet_Link" "https://www.onsemi.com/pub/Collateral/DTC143Z-D.PDF")
    (property "symbolName1" "MUN5233T1G")
)
