(part "MCP2518FDT-H_SL"
    (packageRef "SOIC127P600X175-14N")
    (interface
        (port "1" (symbPinId 1) (portName "TXCAN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "RXCAN") (portType INOUT))
        (port "3" (symbPinId 3) (portName "CLKO/SOF") (portType INOUT))
        (port "4" (symbPinId 4) (portName "%INT%") (portType INOUT))
        (port "5" (symbPinId 5) (portName "OSC2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "OSC1") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VSS") (portType INOUT))
        (port "8" (symbPinId 8) (portName "%INT1%/GPIO1") (portType INOUT))
        (port "9" (symbPinId 9) (portName "%_INT0%/GPIO0/XSTBY") (portType INOUT))
        (port "10" (symbPinId 10) (portName "SCK") (portType INOUT))
        (port "11" (symbPinId 11) (portName "SDI") (portType INOUT))
        (port "12" (symbPinId 12) (portName "SDO") (portType INOUT))
        (port "13" (symbPinId 13) (portName "NCS") (portType INOUT))
        (port "14" (symbPinId 14) (portName "VDD") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "579-MCP2518FDT-H/SL")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Microchip-Technology/MCP2518FDT-H-SL?qs=T3oQrply3y91PFfynJbKYg%3D%3D")
    (property "Manufacturer_Name" "Microchip")
    (property "Manufacturer_Part_Number" "MCP2518FDT-H/SL")
    (property "Description" "CAN Interface IC Stand-alone Low Power CAN FD Controller w/SPI Interface Grade0")
    (property "Datasheet_Link" "https://datasheet.datasheetarchive.com/originals/distributors/Datasheets_SAMA/744760637e861ab0ee43f380fa65a694.pdf")
    (property "symbolName1" "MCP2518FDT-H_SL")
)
