(part "25SVPG270M"
    (packageRef "16SVPT560M")
    (interface
        (port "1" (symbPinId 1) (portName "+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "")
    (property "Mouser_Price/Stock" "")
    (property "Manufacturer_Name" "Panasonic")
    (property "Manufacturer_Part_Number" "25SVPG270M")
    (property "Description" "Low ESR High ripple current 105  5000 h")
    (property "Datasheet_Link" "https://industrial.panasonic.com/cdbs/www-data/pdf/AAB8000/AAB8000C175.pdf")
    (property "symbolName1" "25SVPG270M")
)
