(part "1939870-1"
    (packageRef "19398701")
    (interface
        (port "1" (symbPinId 1) (portName "CD/DAT3") (portType INOUT))
        (port "2" (symbPinId 2) (portName "CMD") (portType INOUT))
        (port "3" (symbPinId 3) (portName "VSS1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VDD") (portType INOUT))
        (port "5" (symbPinId 5) (portName "CLK") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VSS2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "DAT0") (portType INOUT))
        (port "8" (symbPinId 8) (portName "DAT1") (portType INOUT))
        (port "9" (symbPinId 9) (portName "DAT2") (portType INOUT))
        (port "MP1" (symbPinId 10) (portName "MP1") (portType INOUT))
        (port "MP2" (symbPinId 11) (portName "MP2") (portType INOUT))
        (port "MP3" (symbPinId 12) (portName "MP3") (portType INOUT))
        (port "MP4" (symbPinId 13) (portName "MP4") (portType INOUT))
        (port "MP5" (symbPinId 14) (portName "MP5") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "571-1939870-1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity/1939870-1?qs=TL6PIybY3BOt2514n%2FsFbQ%3D%3D")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "1939870-1")
    (property "Description" "Body Features: Primary Product Color Black | Configuration Features: Number of Rows 1 | PCB Mount Orientation Right Angle | Number of Positions 9 | Contact Features: Contact Mating Area Plating Material Thickness .2  .5 MICM | Contact Layout Inline | Contact Current Rating (Max) .5 AMP | Contact Underplating Material Nickel | Contact Mating Area Plating Material Gold | Contact Base Material Copper Alloy | PCB Contact Termination Area Plating Material Tin | Dimensions: Profile Height from PCB .116 INCH | ")
    (property "Datasheet_Link" "https://www.te.com/commerce/DocumentDelivery/DDEController?Action=showdoc&DocId=Customer+Drawing%7F1939870%7FD%7Fpdf%7FJapanese%7FJPN_CD_1939870_D.pdf%7F1939870-1")
    (property "symbolName1" "1939870-1")
)
