(part "CM2021Y330R-10"
    (packageRef "CM2021Y330R10")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "N/A")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Laird/CM2021Y330R-10?qs=PzGy0jfpSMsuvW4RfkrirA%3D%3D")
    (property "Manufacturer_Name" "Laird Technologies")
    (property "Manufacturer_Part_Number" "CM2021Y330R-10")
    (property "Description" "2 Line Common Mode Choke Surface Mount 33 Ohms @ 100 MHz 15A DCR 0.75mOhm 2322 (5956 Metric), 4 Lead  -40C ~ 125C")
    (property "Datasheet_Link" "https://www.laird.com/sites/default/files/cm2021y330r-10-datasheet.pdf")
    (property "symbolName1" "CM2021Y330R-10")
)
