(part "BLM18HE152SN1D"
    (packageRef "BLM18SP221SN1B")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "81-BLM18HE152SN1D")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Murata-Electronics/BLM18HE152SN1D?qs=vNc2DXHODiLhczkT1FKS1Q%3D%3D")
    (property "Manufacturer_Name" "Murata Electronics")
    (property "Manufacturer_Part_Number" "BLM18HE152SN1D")
    (property "Description" "Ferrite Beads 0603 1500ohms")
    (property "Datasheet_Link" "http://www.murata.com/~/media/webrenewal/support/library/catalog/products/emc/emifil/c31e.ashx?la=en-gb")
    (property "symbolName1" "BLM18HE152SN1D")
)
