(part "PESD5V0S1BSF_315"
    (packageRef "PMEG3005AESFYL")
    (interface
        (port "1" (symbPinId 1) (portName "K1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "K2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "771-PESD5V0S1BSF315")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Nexperia/PESD5V0S1BSF315?qs=5eMHoInnifTy2yfigppkSQ%3D%3D")
    (property "Manufacturer_Name" "Nexperia")
    (property "Manufacturer_Part_Number" "PESD5V0S1BSF,315")
    (property "Description" "PESD5V0S1BSF - Ultra low profile bidirectional low capacitance ESD protection diode")
    (property "Datasheet_Link" "https://assets.nexperia.com/documents/data-sheet/PESD5V0S1BSF.pdf")
    (property "symbolName1" "PESD5V0S1BSF_315")
)
