(part "1N4148W-7-F"
    (packageRef "SOD3716X145N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "122")
    (property "Mouser_Part_Number" "621-1N4148W-F")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Diodes-Incorporated/1N4148W-7-F?qs=LHX0FizJzg7Ae9ZM8LTAWw%3D%3D")
    (property "Manufacturer_Name" "Diodes Incorporated")
    (property "Manufacturer_Part_Number" "1N4148W-7-F")
    (property "Description" "Diode Switching 150mA 100V 400mW SOD123 Diodes Inc 1N4148W-7-F Switching Diode 100V, 2-Pin SOD-123")
    (property "Datasheet_Link" "https://www.diodes.com//assets/Datasheets/BAV16W_1N4148W.pdf")
    (property "symbolName1" "1N4148W-7-F")
)
