(part "AP2204K-5_0TRG1"
    (packageRef "SOT95P282X145-5N")
    (interface
        (port "1" (symbPinId 1) (portName "VIN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "EN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "ADJ/NC") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VOUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "621-AP2204K-5.0TRG1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Diodes-Incorporated/AP2204K-5.0TRG1?qs=x6A8l6qLYDBM5Z%2F7Sw%252BT6g%3D%3D")
    (property "Manufacturer_Name" "Diodes Incorporated")
    (property "Manufacturer_Part_Number" "AP2204K-5.0TRG1")
    (property "Description" "0.2A 5V Low Dropout Regulator SOT-23 DiodesZetex AP2204K-5.0TRG1, LDO Voltage Regulator, 200mA, 5 V, 2.3  24 Vin, 5-Pin SOT-23")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/AP2204K-5.0TRG1.pdf")
    (property "symbolName1" "AP2204K-5_0TRG1")
)
