(part "ABM8-40_000MHz-10-D1G-T"
    (packageRef "ABM810000MHZ12D2W")
    (interface
        (port "1" (symbPinId 1) (portName "X1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "X2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "171")
    (property "Mouser_Part_Number" "815-M840000MHZ10D1GT")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/ABRACON/ABM8-40.000MHZ-10-D1G-T?qs=vLWxofP3U2ziONa1hNg0FA%3D%3D")
    (property "Manufacturer_Name" "ABRACON")
    (property "Manufacturer_Part_Number" "ABM8-40.000MHz-10-D1G-T")
    (property "Description" "CERAMIC SMD CRYSTAL")
    (property "Datasheet_Link" "https://abracon.com/Resonators/abm8.pdf")
    (property "symbolName1" "ABM8-40_000MHz-10-D1G-T")
)
