(part "VLS5045EX-6R8M"
    (packageRef "VLS5045EX330M")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Mouser_Part_Number" "810-VLS5045EX-6R8M")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TDK/VLS5045EX-6R8M?qs=oF%2FSscNnLpDYBQmUJumR4g%3D%3D")
    (property "Manufacturer_Name" "TDK")
    (property "Manufacturer_Part_Number" "VLS5045EX-6R8M")
    (property "Description" "TDK VLS-EX Series Type 5045 Shielded Wire-wound SMD Inductor with a Ferrite Core, 6.8 uH +/-20% Wire-Wound 2.9A Idc")
    (property "Datasheet_Link" "https://product.tdk.com/system/files/dam/doc/product/inductor/inductor/smd/catalog/inductor_commercial_power_vls5045ex_en.pdf")
    (property "symbolName1" "VLS5045EX-6R8M")
)
