(part "RQ7E100ATTCR"
    (packageRef "RQ7E100ATTCR")
    (interface
        (port "1" (symbPinId 1) (portName "SOURCE_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "SOURCE_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "SOURCE_3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GATE") (portType INOUT))
        (port "5" (symbPinId 5) (portName "DRAIN_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "DRAIN_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "DRAIN_3") (portType INOUT))
        (port "8" (symbPinId 8) (portName "DRAIN_4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "755-RQ7E100ATTCR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/ROHM-Semiconductor/RQ7E100ATTCR?qs=2WXlatMagcEGRiOPPzGC4A%3D%3D")
    (property "Manufacturer_Name" "ROHM Semiconductor")
    (property "Manufacturer_Part_Number" "RQ7E100ATTCR")
    (property "Description" "RQ7E100ATTCR P-Channel MOSFET, 10 A, 30 V RQ7E100AT, 8-Pin TSMT ROHM")
    (property "Datasheet_Link" "https://fscdn.rohm.com/en/products/databook/datasheet/discrete/transistor/mosfet/rq7e100attcr-e.pdf")
    (property "symbolName1" "RQ7E100ATTCR")
)
