(part "SPM5030T-4R7M-HZ"
    (packageRef "SPM5030")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "810-SPM5030T-4R7M-HZ")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TDK/SPM5030T-4R7M-HZ?qs=lYGu3FyN48eeIkTXE4MIQw%3D%3D")
    (property "Manufacturer_Name" "TDK")
    (property "Manufacturer_Part_Number" "SPM5030T-4R7M-HZ")
    (property "Description" "Inductors for power circuits, Wound metal, Automotive")
    (property "Datasheet_Link" "https://product.tdk.com/system/files/dam/doc/product/inductor/inductor/smd/catalog/inductor_automotive_power_spm5030-hz_en.pdf")
    (property "symbolName1" "SPM5030T-4R7M-HZ")
)
