(part "1747981-1"
    (packageRef "17479811")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
        (port "9" (symbPinId 9) (portName "9") (portType INOUT))
        (port "10" (symbPinId 10) (portName "10") (portType INOUT))
        (port "11" (symbPinId 11) (portName "11") (portType INOUT))
        (port "12" (symbPinId 12) (portName "12") (portType INOUT))
        (port "13" (symbPinId 13) (portName "13") (portType INOUT))
        (port "14" (symbPinId 14) (portName "14") (portType INOUT))
        (port "15" (symbPinId 15) (portName "15") (portType INOUT))
        (port "16" (symbPinId 16) (portName "16") (portType INOUT))
        (port "17" (symbPinId 17) (portName "17") (portType INOUT))
        (port "18" (symbPinId 18) (portName "18") (portType INOUT))
        (port "19" (symbPinId 19) (portName "19") (portType INOUT))
        (port "20" (symbPinId 20) (portName "MH1") (portType INOUT))
        (port "21" (symbPinId 21) (portName "MH2") (portType INOUT))
        (port "22" (symbPinId 22) (portName "MH3") (portType INOUT))
        (port "23" (symbPinId 23) (portName "MH4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "571-1747981-1")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TE-Connectivity/1747981-1?qs=z5WhPA3s7zPU1O1OMn7SIA%3D%3D")
    (property "Manufacturer_Name" "TE Connectivity")
    (property "Manufacturer_Part_Number" "1747981-1")
    (property "Description" "HDMI Receptacle Connector 19 Position Panel Mount; Surface Mount, Right Angle; Through Hole")
    (property "Datasheet_Link" "https://www.digikey.com/htmldatasheets/production/12378/0/0/1/2-1747981-1.pdf")
    (property "symbolName1" "1747981-1")
)
