(part "EEH-ZU1V471UP"
    (packageRef "EEHZS1H151P")
    (interface
        (port "1" (symbPinId 1) (portName "+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "667-EEH-ZU1V471UP")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Panasonic/EEH-ZU1V471UP?qs=HoCaDK9Nz5cz0HnbxgPFpg%3D%3D")
    (property "Manufacturer_Name" "Panasonic")
    (property "Manufacturer_Part_Number" "EEH-ZU1V471UP")
    (property "Description" "Conductive Polymer Hybrid Aluminum Electrolytic Capacitor")
    (property "Datasheet_Link" "https://industrial.panasonic.com/cdbs/www-data/pdf/RDD0000/ast-ind-280898.pdf")
    (property "symbolName1" "EEH-ZU1V471UP")
)
