(part "PUSB3F96X"
    (packageRef "PUSB3F96X")
    (interface
        (port "1" (symbPinId 1) (portName "CH1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "CH2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "CH3") (portType INOUT))
        (port "5" (symbPinId 5) (portName "CH4") (portType INOUT))
        (port "6" (symbPinId 6) (portName "N.C._1") (portType INOUT))
        (port "7" (symbPinId 7) (portName "N.C._2") (portType INOUT))
        (port "8" (symbPinId 8) (portName "GND_2") (portType INOUT))
        (port "9" (symbPinId 9) (portName "N.C._3") (portType INOUT))
        (port "10" (symbPinId 10) (portName "N.C._4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "771-PUSB3F96X")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Nexperia/PUSB3F96X?qs=y2kkmE52mdOojYwbWuCCFg%3D%3D")
    (property "Manufacturer_Name" "Nexperia")
    (property "Manufacturer_Part_Number" "PUSB3F96X")
    (property "Description" "4.6V (Typ) Clamp 5.2A (8/20s) Ipp Tvs Diode Surface Mount DFN2510A-10")
    (property "Datasheet_Link" "https://www.nexperia.com/product/PUSB3F96")
    (property "symbolName1" "PUSB3F96X")
)
