(part "59S20X-400T5-Z"
    (packageRef "59S20X400T5Z")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "476-59S20X-400T5-Z")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Rosenberger/59S20X-400T5-Z?qs=vvQtp7zwQdPV7Wq24wX2xA%3D%3D")
    (property "Manufacturer_Name" "Rosenberger")
    (property "Manufacturer_Part_Number" "59S20X-400T5-Z")
    (property "Description" "RIGHT ANGLE PLUG PCB WITH HOUSING  + 105 C  - 40 C")
    (property "Datasheet_Link" "https://products.rosenberger.com/_ocassets/db/59S20X-400T5-Y.pdf")
    (property "symbolName1" "59S20X-400T5-Z")
)
