(part "SMBJ48A"
    (packageRef "DIOM5436X261N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "576-SMBJ48A")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Littelfuse/SMBJ48A?qs=HR2RnyOI4E5oJjzUW5oszQ%3D%3D")
    (property "Manufacturer_Name" "LITTELFUSE")
    (property "Manufacturer_Part_Number" "SMBJ48A")
    (property "Description" "Diode TVS Single Uni-Dir 48V 600W 2-Pin SMB T/R")
    (property "Datasheet_Link" "https://m.littelfuse.com/~/media/electronics/datasheets/tvs_diodes/littelfuse_tvs_diode_smbj_datasheet.pdf.pdf")
    (property "symbolName1" "SMBJ48A")
)
